[build]
    functions = "functions"
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  force = true
  headers = {X-From = "Netlify"}
  status = 200
[[plugins]]
  package = "@netlify/plugin-functions-install-core"